# Generated by Django 2.2.7 on 2019-11-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20191122_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pubdate',
        ),
        migrations.AddField(
            model_name='author',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='date_udp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date_udp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='emailsubscriber',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emailsubscriber',
            name='date_udp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='emailsubscriber',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='date_udp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='date_udp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
