# Generated by Django 2.2.7 on 2019-11-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_auto_20191122_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='graph.Author'),
        ),
    ]
